name: gametime
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  provider: ^6.1.2
  google_sign_in: ^6.2.1
  font_awesome_flutter: ^10.7.0
  sign_in_with_apple: ^6.1.1
  crypto: ^3.0.3
  english_words: ^4.0.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
      - assets/images/logo.png
      - assets/background/bg1.png
      - assets/background/bg2.jpeg
      - assets/background/bg3.jpeg
      - assets/background/bg4.jpeg