// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVlDWO2u8GCATWi99vP83tOs8pDP6MyrU',
    appId: '1:225621621385:web:c0c49f53973c81ab2a6458',
    messagingSenderId: '225621621385',
    projectId: 'gametime-40f63',
    authDomain: 'gametime-40f63.firebaseapp.com',
    storageBucket: 'gametime-40f63.appspot.com',
    measurementId: 'G-VFJ9Y5SRRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnPUZUf0iySENo-UEqckqcbp7mGCVBdqE',
    appId: '1:225621621385:android:c8fc18b11a446eb22a6458',
    messagingSenderId: '225621621385',
    projectId: 'gametime-40f63',
    storageBucket: 'gametime-40f63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwLG1DSz-5Z6FfTEj4FVvlwQxeMZtvw0w',
    appId: '1:225621621385:ios:38475880e7bd10a12a6458',
    messagingSenderId: '225621621385',
    projectId: 'gametime-40f63',
    storageBucket: 'gametime-40f63.appspot.com',
    iosBundleId: 'com.example.gametime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwLG1DSz-5Z6FfTEj4FVvlwQxeMZtvw0w',
    appId: '1:225621621385:ios:38475880e7bd10a12a6458',
    messagingSenderId: '225621621385',
    projectId: 'gametime-40f63',
    storageBucket: 'gametime-40f63.appspot.com',
    iosBundleId: 'com.example.gametime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVlDWO2u8GCATWi99vP83tOs8pDP6MyrU',
    appId: '1:225621621385:web:c0c49f53973c81ab2a6458',
    messagingSenderId: '225621621385',
    projectId: 'gametime-40f63',
    authDomain: 'gametime-40f63.firebaseapp.com',
    storageBucket: 'gametime-40f63.appspot.com',
    measurementId: 'G-VFJ9Y5SRRY',
  );

}